apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: document-generation-system-sagar
  description: 'TIBCO® Developer Hub Document generation system'
  annotations:
    # github.com/project-slug: TIBCO-Hub-Backstage/tibco-next-demo
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
    - tibco-hub-documentation
spec:
  owner: DocGeneration
  domain: documentation
