apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tibco-flogo-generators
  description: A group of documents
spec:
  owner: tibco-flogo-generators
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: extension-generators-locations
spec:
  targets:
    - ./simple-activity-generator/simple-activity-generator.yaml
    - ./simple-function-generator/simple-function-generator.yaml
    - ./simple-trigger-generator/simple-trigger-generator.yaml
