apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: CarImporter
  description: A company that imports cars
spec:
  type: organization
  profile:
    displayName: Car Importer
    email: info@acme.com
  children: [finance-department, operational-department]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: finance-department
  description: The Finance Department
  tibco.developer.hub/topology:
    theme:
      name: 'orange'
    entityIcon:
      icon: 'https://raw.githubusercontent.com/TIBCOSoftware/tibco-developer-hub/refs/heads/main/tibco-examples/car-order-system-and-components/assets/icons/512/corporate.png'
      iconTooltip: department_icon (flaticon.com)
spec:
  type: department
  profile:
    displayName: The Finance Department
    email: info@acme.com
  parent: CarImporter
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: operational-department
  description: The Operational Department
  tibco.developer.hub/topology:
    theme:
      name: 'orange'
    entityIcon:
      icon: 'https://raw.githubusercontent.com/TIBCOSoftware/tibco-developer-hub/refs/heads/main/tibco-examples/car-order-system-and-components/assets/icons/512/corporate.png'
      iconTooltip: department_icon (flaticon.com)
spec:
  type: department
  profile:
    displayName: The Operational Department
    email: info@acme.com
  parent: CarImporter
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: cars
  description: Everything related to Cars
  tibco.developer.hub/topology:
    theme:
      colors:
        background: hsla(260, 100%, 95%, 1)
        iconColor: hsla(260, 54%, 45%, 1)
spec:
  owner: group:CarImporter
