apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'car-information-provider'
  description: 'Car Information Provider Service'
  tags:
    - backend
    - data-layer
    - flogo
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/tibco-examples
    backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/topology: #optional
    theme:
      colors:
        background: 'lightblue'
        iconColor: 'darkblue'
spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: operational-department
  providesApis: ['car-information-api']
  consumesApis:
    - car-details-api
  dependsOn:
    - resource:default/cars-promotional-materials
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: 'car-information-api'
  description: 'An API that provides car details, and points to resources'
  tags:
    - store
    - rest
  tibco.developer.hub/topology: #optional
    theme:
      name: yellow
    entityIcon:
      icon: https://raw.githubusercontent.com/TIBCOSoftware/tibco-developer-hub/refs/heads/main/tibco-examples/car-order-system-and-components/assets/icons/512/cloud_api.png
      iconTooltip: cloud_api (flaticon.com)
spec:
  type: openapi
  lifecycle: production
  system: car-order-system
  owner: operational-department
  apiConsumedBy: ['component:car-order-ui']
  definition:
    $text: ./sample-api.json
