apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'car-analyzer'
  description: 'Car Analytical Report'
  tags:
    - spotfire
    - data-layer
    - frontend
  links:
    - title: TIBCO Spotfire Home
      url: https://www.tibco.com/products/tibco-spotfire
    - title: Demos
      url: https://www.tibco.com/products/tibco-spotfire/learn/demos
  annotations:
    github.com/project-slug: TIBCO-Hub-Backstage/tibco-examples
    backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/topology: #optional
    entityIcon:
      icon: https://raw.githubusercontent.com/TIBCOSoftware/tibco-developer-hub/refs/heads/main/tibco-examples/car-order-system-and-components/assets/icons/512/report_analysis.png
      iconTooltip: report (flaticon.com)
    statusIcons:
      - icon: NewReleases
        iconColor: pink
        iconTooltip: New Released!
      - icon: AssignmentTurnedIn
        iconColor: seagreen
        iconTooltip: Report Validated

spec:
  type: service
  lifecycle: production
  system: car-order-system
  owner: finance-department
  dependsOn:
    - resource:default/cars-database
    - resource:default/cars-promotional-materials
