apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: self-service-build-deploy-bw5ce-app-location
  description: Build & Deploy BW5CE App self service flow
spec:
  targets:
    - ./self-service-build-deploy-bw5ce-app.yaml
    - ../tibco-self-service-group.yaml
